-- FICHA
CREATE TABLE pv1 (
  P1_CONT int(11) NOT NULL AUTO_INCREMENT,
  P1_FICHA varchar(10) NOT NULL,
  P1_DESCR_FICHA varchar(30) NOT NULL, -- PADRAO
  P1_TIPO varchar(15) NOT NULL,        -- BALCAO, MESA, CONVENIENCIA
  P1_SITUACAO varchar(15) NOT NULL,    -- 1-ABERTA, 2-EM-CONSUMO, 3-FECHADA, 4-FINALIZADA
  P1_VL_TOTAL float NULL,
  P1_VL_ACUMULADO float NULL,
  CONSTRAINT pk_ficha PRIMARY KEY (P1_CONT)
);

-- LISTA PRECOS
CREATE TABLE pv2 (
  P2_CONT int(11) NOT NULL AUTO_INCREMENT,
  P2_PROD varchar(15) NOT NULL,
  P2_DESCR_PROD varchar(50) NOT NULL,
  P2_UM varchar(10) NOT NULL,
  P2_PRECO float NULL,
  P2_FAMILIA varchar(15) NOT NULL,  -- CERVEJAS, SUCOS, REFRIGERANTES, CAFES, APERITIVOS, LANCHES, PORÇÕES, PIZZAS, SALGADOS, DOCES, PÃES, BOLOS, TORTAS, REFEIÇÃO, CALDOS, OUTROS
  P2_DATA_VAL date NULL,  -- DATA VALIDADE PRECO
  P2_DATA_ATU date NULL,  -- DATA ATUALIZACAO
  CONSTRAINT pk_precos PRIMARY KEY (P2_CONT)
);

-- CONSUMO
CREATE TABLE pv3 (
  P3_CONT int(11) NOT NULL AUTO_INCREMENT,
  P3_TIPO varchar(15) NOT NULL,        -- BALCAO, MESA, CONVENIENCIA
  P3_FICHA varchar(10) NOT NULL,
  P3_PROD varchar(15) NOT NULL,
  P3_DESCR_PROD varchar(50) NOT NULL,
  P3_UM varchar(10) NOT NULL,
  P3_QTD int(06) NULL,
  P3_PRECO float NULL,
  P3_VL_TOTAL float NULL,
  P3_DATA date NULL,  -- DATA ATUAL
  P3_HORA time NULL,  -- HORA ATUAL
  CONSTRAINT pk_consumo PRIMARY KEY (P3_CONT)
);

-- PAGAMENTO
CREATE TABLE pv4 (
  P4_CONT int(11) NOT NULL AUTO_INCREMENT,
  P4_FICHA varchar(10) NOT NULL,
  P4_TIPO varchar(15) NOT NULL,        -- BALCAO, MESA, CONVENIENCIA
  P4_SITUACAO varchar(15) NOT NULL,    -- 1-ABERTA, 2-EM-CONSUMO, 3-FECHADA, 4-PAGAMENTO
  P4_FORMA_PAGTO varchar(10) NOT NULL, -- DINHEIRO, DEBITO, CREDITO, PIX, OUTROS
  P4_VL_TOTAL float NULL,
  P4_VL_PAGO float NULL,
  P4_VL_TROCO float NULL,
  P4_DATA date NULL,  -- DATA ATUAL
  P4_HORA time NULL,  -- HORA ATUAL
  CONSTRAINT pk_pagamento PRIMARY KEY (P4_CONT)
);

-- MOVIMENTO DE CONSUMO
CREATE TABLE pv5 (
  P5_CONT int(11) NOT NULL AUTO_INCREMENT,
  P5_TIPO varchar(15) NOT NULL,        -- BALCAO, MESA, CONVENIENCIA
  P5_FICHA varchar(10) NOT NULL,
  P5_PROD varchar(15) NOT NULL,
  P5_DESCR_PROD varchar(50) NOT NULL,
  P5_UM varchar(10) NOT NULL,
  P5_QTD int(06) NULL,
  P5_PRECO float NULL,
  P5_VL_TOTAL float NULL,
  P5_DATA date NULL,  -- DATA ATUAL
  P5_HORA time NULL,  -- HORA ATUAL
  CONSTRAINT pk_consumo PRIMARY KEY (P5_CONT)
);



